/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.ModeloPaciente;
import Modelo.ModeloTabela;
import ModeloConexao.ConexaoBD;
import ModeloDAO.DAOPaciente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Henrique
 */
public class FormHistoricoPacientes extends javax.swing.JFrame {
         ConexaoBD conex = new ConexaoBD();
      
         ModeloPaciente paciente = new ModeloPaciente();
         DAOPaciente daoPac = new DAOPaciente();
    /**
     * Creates new form FormHistoricoPacientes
     */
    public FormHistoricoPacientes() {
        initComponents();
        preencherTabela("select *from concluir");
    }
    
    
    public void preencherTabela(String Sql){
        
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID","Paciente","Medico","receita","Nascimento","Diagnostico"};//titulos das coluna da tabela
        //abre conexao
        conex.Conexao();
        //executa busca no banco
        conex.ExecutaSql(Sql);
        
        try{
            //filtra primeiro resultado
            conex.rs.first();
            do{
                //insere no arraylist o que esta no atributo codigo nome ... no banco de dados
                dados.add(new Object[]{conex.rs.getInt("codigoConcluir"),conex.rs.getString("nomePac"),conex.rs.getString("nomeMed"),conex.rs.getString("receita"),conex.rs.getString("nascPac"),conex.rs.getString("diagnostico")});
               //enquanto tiver registro na tabela do banco
            }while(conex.rs.next());
        }catch(Exception e){
            //se algo deu errdo
            JOptionPane.showMessageDialog(null, "busque novamente");
        }
        //instancia tablea com os dados e coluna como parametro
        ModeloTabela modelotabela = new ModeloTabela(dados, colunas);
        //seta o modelo tabela
        tabelahistoricopaciente.setModel(modelotabela);
        
        //dimensiona tamanho da coluna 0
        tabelahistoricopaciente.getColumnModel().getColumn(0).setPreferredWidth(90);
        tabelahistoricopaciente.getColumnModel().getColumn(0).setResizable(false);//nao permite redimensionamento
        
        tabelahistoricopaciente.getColumnModel().getColumn(1).setPreferredWidth(196);  //dimensiona tamanho da coluna 1
        tabelahistoricopaciente.getColumnModel().getColumn(1).setResizable(false);//nao permite redimensionamento
        
        tabelahistoricopaciente.getColumnModel().getColumn(2).setPreferredWidth(90);  //dimensiona tamanho da coluna 2
        tabelahistoricopaciente.getColumnModel().getColumn(2).setResizable(false);//nao permite redimensionamento
        
        tabelahistoricopaciente.getColumnModel().getColumn(3).setPreferredWidth(90);  //dimensiona tamanho da coluna 3
        tabelahistoricopaciente.getColumnModel().getColumn(3).setResizable(false);//nao permite redimensionamento
       
        tabelahistoricopaciente.getColumnModel().getColumn(4).setPreferredWidth(90);  //dimensiona tamanho da coluna 3
        tabelahistoricopaciente.getColumnModel().getColumn(4).setResizable(false);
        
        tabelahistoricopaciente.getColumnModel().getColumn(5).setPreferredWidth(190);  //dimensiona tamanho da coluna 2
        tabelahistoricopaciente.getColumnModel().getColumn(5).setResizable(false);
        
        tabelahistoricopaciente.getTableHeader().setReorderingAllowed(false);//nao permite reordenar a tabela
        tabelahistoricopaciente.setAutoResizeMode(tabelahistoricopaciente.AUTO_RESIZE_OFF);//nao permite redimensionar a tabela
        
        tabelahistoricopaciente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//so permite que um nome seja selecionado 
             //fecha conexao   
        conex.Desconecta();
    
    
    
    
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelahistoricopaciente = new javax.swing.JTable();
        pesquisarPaciente = new javax.swing.JTextField();
        Pesquiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpanel.setLayout(null);

        tabelahistoricopaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelahistoricopaciente);

        jpanel.add(jScrollPane1);
        jScrollPane1.setBounds(10, 95, 750, 360);
        jpanel.add(pesquisarPaciente);
        pesquisarPaciente.setBounds(10, 20, 370, 30);

        Pesquiar.setText("Pesquisar");
        Pesquiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquiarActionPerformed(evt);
            }
        });
        jpanel.add(Pesquiar);
        Pesquiar.setBounds(390, 20, 90, 30);

        getContentPane().add(jpanel);
        jpanel.setBounds(10, 10, 780, 470);

        setSize(new java.awt.Dimension(818, 529));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PesquiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquiarActionPerformed
        paciente.setNome(pesquisarPaciente.getText());
        ModeloPaciente pac1 = daoPac.buscaPaciente(paciente);
        String nome = pac1.getNome();
        
        preencherTabela("SELECT  *FROM concluir WHERE nomePac like'%"+nome+"%'");
    }//GEN-LAST:event_PesquiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHistoricoPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHistoricoPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHistoricoPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHistoricoPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHistoricoPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pesquiar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanel;
    private javax.swing.JTextField pesquisarPaciente;
    private javax.swing.JTable tabelahistoricopaciente;
    // End of variables declaration//GEN-END:variables
}
