/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.Hora;
import Modelo.ModeloAgendaConsulta;
import Modelo.ModeloConcluir;
import ModeloDAO.DAOAgenda;
import ModeloDAO.DAOConcluir;
import java.text.DateFormat;
import java.util.Date;
import javafx.scene.input.DataFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Henrique
 */
public class FormularioConsulta extends javax.swing.JFrame {

    String cod_agenda;
    ModeloAgendaConsulta mac = new ModeloAgendaConsulta();
    DAOAgenda daogenda = new DAOAgenda();
    
    DAOConcluir concluir = new DAOConcluir();
    ModeloConcluir mc = new ModeloConcluir();
    /**
     * Creates new form FormularioConsulta
     */
    public FormularioConsulta(String codigo) {
        initComponents();
        cod_agenda=codigo;
        int cod = Integer.parseInt(cod_agenda);
         mac=daogenda.BuscaAgendamentoPorCodigo(cod);
         nome.setText(mac.getNomepaciente());
         nascimento.setText(mac.getPacienteNasc());
         motivo.setText(mac.getMotivo());
         nomemedico.setText(mac.getNomemedico());
        diagnostico.setEnabled(true);
        receita.setEnabled(true);
        
         Date data = new Date();
         DateFormat formata = DateFormat.getDateInstance(DateFormat.LONG);
         ldata.setText(formata.format(data));
          
         Hora mostrahora = new Hora();
         mostrahora.LerHora();
         lhora.setText("hora atual: "+mostrahora.hora);
          timer1.start();
         
    }

    private FormularioConsulta() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        motivo = new javax.swing.JTextArea();
        nascimento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        receita = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        diagnostico = new javax.swing.JTextArea();
        finalizar = new javax.swing.JButton();
        medico = new javax.swing.JLabel();
        nomemedico = new javax.swing.JLabel();
        lhora = new javax.swing.JLabel();
        ldata = new javax.swing.JLabel();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atendimento");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setText("Nome");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 60, 14);

        jLabel3.setText("Motivo");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 50, 70, 14);

        jLabel4.setText("Nascimento");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(480, 10, 70, 14);

        nome.setEnabled(false);
        jPanel1.add(nome);
        nome.setBounds(50, 10, 390, 30);

        motivo.setColumns(20);
        motivo.setRows(5);
        motivo.setEnabled(false);
        jScrollPane1.setViewportView(motivo);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 50, 620, 100);

        nascimento.setEnabled(false);
        jPanel1.add(nascimento);
        nascimento.setBounds(550, 10, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 50, 690, 160);

        jLabel1.setText("Paciente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 70, 20);

        jLabel5.setText("Médico");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 464, 60, 20);

        jLabel6.setText("Diagnóstico");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 230, 90, 14);

        jLabel7.setText("Receita");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 340, 70, 14);

        receita.setColumns(20);
        receita.setRows(5);
        receita.setEnabled(false);
        jScrollPane2.setViewportView(receita);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(80, 340, 620, 100);

        diagnostico.setColumns(20);
        diagnostico.setRows(5);
        diagnostico.setEnabled(false);
        jScrollPane3.setViewportView(diagnostico);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(80, 230, 620, 100);

        finalizar.setText("Finalizar");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });
        getContentPane().add(finalizar);
        finalizar.setBounds(250, 460, 250, 23);
        getContentPane().add(medico);
        medico.setBounds(80, 200, 140, 0);
        getContentPane().add(nomemedico);
        nomemedico.setBounds(80, 460, 160, 30);
        getContentPane().add(lhora);
        lhora.setBounds(200, 10, 170, 20);
        getContentPane().add(ldata);
        ldata.setBounds(440, 10, 170, 20);

        setSize(new java.awt.Dimension(752, 546));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
  
        
            mc.setNomePaciente(nome.getText());
            mc.setNomeMedico(nomemedico.getText());
            mc.setNascPac(nascimento.getText());
            mc.setDiagnostico(diagnostico.getText());
            mc.setReceita(receita.getText());
            concluir.Salvar(mc);
            JOptionPane.showMessageDialog(null,"finalizado com sucesso");
            nome.setText("");
            nomemedico.setText("");
            nascimento.setText("");
            receita.setText("");
            diagnostico.setText("");
        
            
    }//GEN-LAST:event_finalizarActionPerformed

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
             
                       Hora mostrahora = new Hora();
                       mostrahora.LerHora();
                       lhora.setText("hora atual: "+mostrahora.hora);
                      
        
        
    }//GEN-LAST:event_timer1OnTime

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea diagnostico;
    private javax.swing.JButton finalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel ldata;
    private javax.swing.JLabel lhora;
    private javax.swing.JLabel medico;
    private javax.swing.JTextArea motivo;
    private javax.swing.JTextField nascimento;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel nomemedico;
    private javax.swing.JTextArea receita;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables
}
