/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.ModeloAgendaConsulta;
import Modelo.ModeloTabela;
import ModeloConexao.ConexaoBD;
import ModeloDAO.DAOAgenda;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Henrique
 */
public class FormularioAgendados extends javax.swing.JFrame {
    ConexaoBD conex = new ConexaoBD();
    ModeloAgendaConsulta modagenda = new ModeloAgendaConsulta();
    ModeloAgendaConsulta agenda = new ModeloAgendaConsulta();
    DAOAgenda daoagenda = new DAOAgenda();
    String dthoje;
    String status;
    /**
     * Creates new form FormularioAgendamento
     */
    public FormularioAgendados() {
        initComponents();
        Calendar data = Calendar.getInstance();
        Date d = data.getTime();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        dateFormat.format(d);
        
        
        dthoje=dateFormat.format(d);
        status ="em aberto";
        
        preencherTabela("SELECT *FROM agenda INNER JOIN pacientes on agenda.codigo_pacienteagenda = pacientes.codigo INNER JOIN medicos on agenda.codigo_medicoagenda = medicos.codigo and agenda_status='"+status+"'order by agenda_data");
        //select *from agenda inner join pacientes on agenda.codigo_pacienteagenda=pacientes.codigo inner JOIN medicos on agenda.codigo_medicoagenda=medicos.codigo where agenda_data = '2018-05-09
       // select *from agenda inner join pacientes on agenda.codigo_pacienteagenda=pacientes.codigo inner JOIN medicos on agenda.codigo_medicoagenda=medicos.codigo where agenda_data = '2018-05-09' ORDER BY codigo_agenda;
    }
    
     public void preencherTabela(String Sql){
        
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID","Paciente","Data","Status","Medico"};//titulos das coluna da tabela
        //abre conexao
        conex.Conexao();
        //executa busca no banco
        conex.ExecutaSql(Sql);
        
        try{
            //filtra primeiro resultado
            conex.rs.first();
            do{
                //insere no arraylist o que esta no atributo codigo nome ... no banco de dados
                dados.add(new Object[]{conex.rs.getInt("codigo_agenda"),conex.rs.getString("nome"),conex.rs.getString("agenda_data"),conex.rs.getString("agenda_status"),conex.rs.getString("nomemed")});
               //enquanto tiver registro na tabela do banco
            }while(conex.rs.next());
        }catch(Exception e){
            //se algo deu errdo
            JOptionPane.showMessageDialog(null, "busque novamente");
        }
        //instancia tablea com os dados e coluna como parametro
        ModeloTabela modelotabela = new ModeloTabela(dados, colunas);
        //seta o modelo tabela
        tabelaagenda.setModel(modelotabela);
        
        //dimensiona tamanho da coluna 0
        tabelaagenda.getColumnModel().getColumn(0).setPreferredWidth(90);
        tabelaagenda.getColumnModel().getColumn(0).setResizable(false);//nao permite redimensionamento
        
        tabelaagenda.getColumnModel().getColumn(1).setPreferredWidth(196);  //dimensiona tamanho da coluna 1
        tabelaagenda.getColumnModel().getColumn(1).setResizable(false);//nao permite redimensionamento
        
        tabelaagenda.getColumnModel().getColumn(2).setPreferredWidth(90);  //dimensiona tamanho da coluna 2
        tabelaagenda.getColumnModel().getColumn(2).setResizable(false);//nao permite redimensionamento
        
        tabelaagenda.getColumnModel().getColumn(3).setPreferredWidth(90);  //dimensiona tamanho da coluna 3
        tabelaagenda.getColumnModel().getColumn(3).setResizable(false);//nao permite redimensionamento
       
        tabelaagenda.getColumnModel().getColumn(4).setPreferredWidth(190);  //dimensiona tamanho da coluna 3
        tabelaagenda.getColumnModel().getColumn(4).setResizable(false);
        
        tabelaagenda.getTableHeader().setReorderingAllowed(false);//nao permite reordenar a tabela
        tabelaagenda.setAutoResizeMode(tabelaagenda.AUTO_RESIZE_OFF);//nao permite redimensionar a tabela
        
        tabelaagenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//so permite que um nome seja selecionado 
             //fecha conexao   
        conex.Desconecta();
    
    
    
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaagenda = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        atender = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        tabelaagenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabelaagenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaagenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaagendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaagenda);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 40, 610, 300);

        jLabel2.setText("Agenda para hoje");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 20, 100, 14);

        atender.setText("Atender");
        atender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atenderActionPerformed(evt);
            }
        });
        jPanel1.add(atender);
        atender.setBounds(180, 360, 300, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(22, 45, 670, 400);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Agenda");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 20, 120, 17);

        setSize(new java.awt.Dimension(739, 517));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaagendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaagendaMouseClicked
      
        
          //quando clica em um nome da tabela 
        String codigo_agendados = ""+tabelaagenda.getValueAt(tabelaagenda.getSelectedRow(),0);//
      
        //abre conexao
      conex.Conexao();
      //executa select com o nome selecionado na tabela
      conex.ExecutaSql("select *from agenda where codigo_agenda='"+codigo_agendados+"'");
      try{
          //filtra o primeiro resultado
      conex.rs.first();
      agenda.setStatus("em atendimento");
      agenda.setCodigoconsulta(conex.rs.getInt("codigo_agenda"));
      }catch(Exception e){
          //mostra mensafem se algo nao funcionou
          JOptionPane.showMessageDialog(null, "erro no evento mouseclicked");
      }
      //desconecta
      conex.Desconecta();
    
    }//GEN-LAST:event_tabelaagendaMouseClicked

    private void atenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atenderActionPerformed
        daoagenda.Alterar(agenda);
        preencherTabela("SELECT *FROM agenda INNER JOIN pacientes on agenda.codigo_pacienteagenda = pacientes.codigo INNER JOIN medicos on agenda.codigo_medicoagenda = medicos.codigo and agenda_status='"+status+"'order by agenda_data");
    }//GEN-LAST:event_atenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioAgendados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioAgendados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioAgendados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioAgendados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioAgendados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaagenda;
    // End of variables declaration//GEN-END:variables
}
