/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.ModeloAgendaConsulta;
import Modelo.ModeloTabela;
import ModeloConexao.ConexaoBD;
import ModeloDAO.DAOAgenda;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Henrique
 */
public class FormularioAgendaMedico extends javax.swing.JFrame {

    ConexaoBD conexao = new ConexaoBD();
    DAOAgenda daoagenda = new DAOAgenda();
    String codAg;
    String dthoje;
    String status;
    /**
     * Creates new form FormularioAgendaMedico
     */
    public FormularioAgendaMedico() {
        initComponents();
        
        Calendar data = Calendar.getInstance();
        Date d = data.getTime();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        dateFormat.format(d);
        dthoje=dateFormat.format(d);
        status ="em atendimento";
        
        PreencherMedicos();
    }

    
     public void PreencherMedicos(){
     
        conexao.Conexao();
        try {
             conexao.ExecutaSql("select *from medicos order by nomemed");
             conexao.rs.first();
             nomemedico.removeAllItems();
             do{
                 nomemedico.addItem(conexao.rs.getString("nomemed"));
             }while(conexao.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
         conexao.Desconecta();
    }
     
      public void preencherTabela(String Sql){
        
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID","Paciente","Data","Status","Medico"};//titulos das coluna da tabela
        //abre conexao
        conexao.Conexao();
        //executa busca no banco
        conexao.ExecutaSql(Sql);
        
        try{
            //filtra primeiro resultado
            conexao.rs.first();
            do{
                //insere no arraylist o que esta no atributo codigo nome ... no banco de dados
                dados.add(new Object[]{conexao.rs.getInt("codigo_agenda"),conexao.rs.getString("nome"),conexao.rs.getString("agenda_data"),conexao.rs.getString("agenda_status"),conexao.rs.getString("nomemed")});
               //enquanto tiver registro na tabela do banco
            }while(conexao.rs.next());
        }catch(Exception e){
            //se algo deu errdo
            JOptionPane.showMessageDialog(null, "busque novamente");
        }
        //instancia tablea com os dados e coluna como parametro
        ModeloTabela modelotabela = new ModeloTabela(dados, colunas);
        //seta o modelo tabela
        tabelapaciente.setModel(modelotabela);
        
        //dimensiona tamanho da coluna 0
        tabelapaciente.getColumnModel().getColumn(0).setPreferredWidth(90);
        tabelapaciente.getColumnModel().getColumn(0).setResizable(false);//nao permite redimensionamento
        
        tabelapaciente.getColumnModel().getColumn(1).setPreferredWidth(196);  //dimensiona tamanho da coluna 1
        tabelapaciente.getColumnModel().getColumn(1).setResizable(false);//nao permite redimensionamento
        
        tabelapaciente.getColumnModel().getColumn(2).setPreferredWidth(90);  //dimensiona tamanho da coluna 2
        tabelapaciente.getColumnModel().getColumn(2).setResizable(false);//nao permite redimensionamento
        
        tabelapaciente.getColumnModel().getColumn(3).setPreferredWidth(90);  //dimensiona tamanho da coluna 3
        tabelapaciente.getColumnModel().getColumn(3).setResizable(false);//nao permite redimensionamento
       
        tabelapaciente.getColumnModel().getColumn(4).setPreferredWidth(190);  //dimensiona tamanho da coluna 3
        tabelapaciente.getColumnModel().getColumn(4).setResizable(false);
        
        tabelapaciente.getTableHeader().setReorderingAllowed(false);//nao permite reordenar a tabela
        tabelapaciente.setAutoResizeMode(tabelapaciente.AUTO_RESIZE_OFF);//nao permite redimensionar a tabela
        
        tabelapaciente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//so permite que um nome seja selecionado 
             //fecha conexao   
        conexao.Desconecta();
    
    
    
    
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nomemedico = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelapaciente = new javax.swing.JTable();
        atender = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Agenda");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 10, 170, 20);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setText("Médico");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(420, 20, 50, 14);

        nomemedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        nomemedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomemedicoMouseClicked(evt);
            }
        });
        nomemedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomemedicoActionPerformed(evt);
            }
        });
        jPanel1.add(nomemedico);
        nomemedico.setBounds(470, 20, 180, 20);

        tabelapaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelapaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelapacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelapaciente);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 80, 610, 220);

        atender.setText("Atender");
        atender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atenderActionPerformed(evt);
            }
        });
        jPanel1.add(atender);
        atender.setBounds(210, 310, 260, 23);

        jLabel3.setText("Pacientes");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 50, 110, 14);

        buscar.setText("buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar);
        buscar.setBounds(500, 50, 100, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 690, 350);

        setSize(new java.awt.Dimension(728, 443));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
       int cod = daoagenda.CodigoMedico((String) nomemedico.getSelectedItem());
       String codigo = String.valueOf(cod);
        preencherTabela("SELECT *from agenda inner JOIN pacientes on agenda.codigo_pacienteagenda=pacientes.codigo INNER JOIN medicos on agenda.codigo_medicoagenda = medicos.codigo WHERE medicos.codigo='"+codigo+"'");
    }//GEN-LAST:event_buscarActionPerformed

    private void atenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atenderActionPerformed
           
        FormularioConsulta fc = new FormularioConsulta(codAg);
        fc.setVisible(true);
        dispose();
    }//GEN-LAST:event_atenderActionPerformed

    private void tabelapacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelapacienteMouseClicked
      codAg=""+tabelapaciente.getValueAt(tabelapaciente.getSelectedRow(), 0);
        
    }//GEN-LAST:event_tabelapacienteMouseClicked

    private void nomemedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomemedicoMouseClicked
    //   int cod = daoagenda.CodigoMedico((String) nomemedico.getSelectedItem());
    //   String codigo = String.valueOf(cod);
    //    preencherTabela("SELECT *from agenda inner JOIN pacientes on agenda.codigo_pacienteagenda=pacientes.codigo INNER JOIN medicos on agenda.codigo_medicoagenda = medicos.codigo WHERE medicos.codigo='"+codigo+"'");
    }//GEN-LAST:event_nomemedicoMouseClicked

    private void nomemedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomemedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomemedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioAgendaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioAgendaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioAgendaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioAgendaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioAgendaMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atender;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> nomemedico;
    private javax.swing.JTable tabelapaciente;
    // End of variables declaration//GEN-END:variables
}
