/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import ModeloConexao.ConexaoBD;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Henrique
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD();
    FormularioMedico formulariomedico = new FormularioMedico();
    FormularioUsuario formulariousuario = new FormularioUsuario();
    FormularioPaciente formulariopaciente = new FormularioPaciente();
    FormularioAgenda formularioagenda = new FormularioAgenda();
    FormularioAgendados formagendados = new FormularioAgendados();
    FormularioAgendaMedico foragendamedico = new FormularioAgendaMedico();
    FormHistoricoPacientes fhp = new FormHistoricoPacientes();
    
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(String usuario) {
        initComponents();
        labelusuario.setText(usuario);
        conecta.Conexao();
       
    }

    TelaPrincipal() {
         
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agendados = new javax.swing.JButton();
        btnprincipalmedico = new javax.swing.JButton();
        btnprincipalagenda = new javax.swing.JButton();
        btnprincipaluser = new javax.swing.JButton();
        btnprincipalpaciente = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        labelusuario = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        agendaMedico = new javax.swing.JButton();
        lbfundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemPaciente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinica");
        setResizable(false);
        getContentPane().setLayout(null);

        agendados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        agendados.setForeground(new java.awt.Color(102, 102, 102));
        agendados.setText("Agendados");
        agendados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendadosActionPerformed(evt);
            }
        });
        getContentPane().add(agendados);
        agendados.setBounds(40, 80, 130, 23);

        btnprincipalmedico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnprincipalmedico.setForeground(new java.awt.Color(102, 102, 102));
        btnprincipalmedico.setText("Médicos");
        btnprincipalmedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprincipalmedicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnprincipalmedico);
        btnprincipalmedico.setBounds(40, 140, 130, 20);

        btnprincipalagenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnprincipalagenda.setForeground(new java.awt.Color(102, 102, 102));
        btnprincipalagenda.setText("Agendar");
        btnprincipalagenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprincipalagendaActionPerformed(evt);
            }
        });
        getContentPane().add(btnprincipalagenda);
        btnprincipalagenda.setBounds(40, 110, 130, 23);

        btnprincipaluser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnprincipaluser.setForeground(new java.awt.Color(102, 102, 102));
        btnprincipaluser.setText("Usuários");
        btnprincipaluser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprincipaluserActionPerformed(evt);
            }
        });
        getContentPane().add(btnprincipaluser);
        btnprincipaluser.setBounds(40, 170, 130, 23);

        btnprincipalpaciente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnprincipalpaciente.setForeground(new java.awt.Color(102, 102, 102));
        btnprincipalpaciente.setText("Pacientes");
        btnprincipalpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprincipalpacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnprincipalpaciente);
        btnprincipalpaciente.setBounds(40, 200, 130, 23);

        btn_sair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_sair.setForeground(new java.awt.Color(102, 102, 102));
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sair);
        btn_sair.setBounds(40, 230, 130, 23);
        getContentPane().add(labelusuario);
        labelusuario.setBounds(70, 640, 140, 20);

        user.setText("usuário:");
        getContentPane().add(user);
        user.setBounds(20, 640, 60, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensclin/bemvindo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 220, 360, 250);

        agendaMedico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        agendaMedico.setForeground(new java.awt.Color(102, 102, 102));
        agendaMedico.setText("Agenda Médico");
        agendaMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(agendaMedico);
        agendaMedico.setBounds(40, 50, 130, 23);

        lbfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensclin/fundo1.jpg"))); // NOI18N
        lbfundo.setEnabled(false);
        getContentPane().add(lbfundo);
        lbfundo.setBounds(-10, -30, 1370, 720);

        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jMenu2.setText("Consultas");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Pendencias");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Prontuario");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Historico");

        jMenuItemPaciente.setText("Pacientes");
        jMenuItemPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPacienteActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemPaciente);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1366, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnprincipalmedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprincipalmedicoActionPerformed
       
        conecta.ExecutaSql("select *from usuarios where nome='"+labelusuario.getText()+"'");
        try {
            conecta.rs.first();
            if(conecta.rs.getString("tipo").equals("administrador")){
                if(formulariomedico == null){
                    formulariomedico = new FormularioMedico();
                    formulariomedico.setVisible(true);
                    formulariomedico.setResizable(false);
                }else{
                    formulariomedico.setVisible(true);
                    formulariomedico.setResizable(false);
                }
                
               //  FormularioMedico formulariomedico = new FormularioMedico();
               //  formulariomedico.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "voce precisa de permisao de adminstrador\n para acessar esta area ");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "voce precisa de permisao de adminstrador\n para acessar esta area "+e);
        }
        
        
         
         
    }//GEN-LAST:event_btnprincipalmedicoActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        
        conecta.Desconecta();
        dispose();
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btnprincipaluserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprincipaluserActionPerformed
         conecta.ExecutaSql("select *from usuarios where nome='"+labelusuario.getText()+"'");
        try {
            conecta.rs.first();
            if(conecta.rs.getString("tipo").equals("administrador")){
                if(formulariousuario == null){
                    formulariousuario = new FormularioUsuario();
                    formulariousuario.setVisible(true);
                    formulariousuario.setResizable(false);
                }else{
                    formulariousuario.setVisible(true);
                    formulariousuario.setResizable(false);
                }
                
               //  FormularioMedico formulariomedico = new FormularioMedico();
               //  formulariomedico.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "voce precisa de permisao de adminstrador\n para acessar esta area ");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "voce precisa de permisao de adminstrador\n para acessar esta area "+e);
        }   
        
       // formulariousuario.setVisible(true);
         
    }//GEN-LAST:event_btnprincipaluserActionPerformed

    private void btnprincipalagendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprincipalagendaActionPerformed
       
       formularioagenda.setVisible(true);
        
       
    }//GEN-LAST:event_btnprincipalagendaActionPerformed

    private void btnprincipalpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprincipalpacienteActionPerformed
        conecta.ExecutaSql("select *from usuarios where nome='"+labelusuario.getText()+"'");
        try {
            conecta.rs.first();
            if(conecta.rs.getString("tipo").equals("administrador")){
                if(formulariopaciente == null){
                    formulariopaciente = new FormularioPaciente();
                    formulariopaciente.setVisible(true);
                    formulariopaciente.setResizable(false);
                }else{
                    formulariopaciente.setVisible(true);
                    formulariopaciente.setResizable(false);
                }
                
               //  FormularioMedico formulariomedico = new FormularioMedico();
               //  formulariomedico.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "voce precisa de permisao de adminstrador\n para acessar esta area ");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "voce precisa de permisao de adminstrador\n para acessar esta area "+e);
        }
     //  formulariopaciente.setVisible(true);
        
    }//GEN-LAST:event_btnprincipalpacienteActionPerformed

    private void agendadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendadosActionPerformed
         formagendados.setVisible(true);
    }//GEN-LAST:event_agendadosActionPerformed

    private void agendaMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaMedicoActionPerformed
        foragendamedico.setVisible(true);
    }//GEN-LAST:event_agendaMedicoActionPerformed

    private void jMenuItemPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPacienteActionPerformed
                  
        fhp.setVisible(true);
    }//GEN-LAST:event_jMenuItemPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendaMedico;
    private javax.swing.JButton agendados;
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton btnprincipalagenda;
    private javax.swing.JButton btnprincipalmedico;
    private javax.swing.JButton btnprincipalpaciente;
    private javax.swing.JButton btnprincipaluser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemPaciente;
    private javax.swing.JLabel labelusuario;
    private javax.swing.JLabel lbfundo;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
